dev3/demo3/urls.py
from django.conf.urls import url

from . import views

app_name='demo3'

urlpatterns=[
    url('^$',views.index,name='index'),
    url('^detail/(\d+)/$',views.detail,name='detail'),
    url('^poll/(\d+)/$',views.poll,name='poll'),

]

dev3/dev3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('demo3/',include('demo3.urls',namespace='demo3'))
]

dev3/demo3/models.py
from django.db import models

# Create your models here.

class Problem(models.Model):
    pname=models.CharField(max_length=200)

    def __str__(self):
        return self.pname

class Option(models.Model):
    oname=models.CharField(max_length=100)
    oshu=models.IntegerField(default=0)
    pid=models.ForeignKey('Problem',on_delete=models.CASCADE)

    def __str__(self):
        return self.oname

dev3/demo3/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,Http404

from .models import Problem,Option

# Create your views here.


def index(request):
    listp= Problem.objects.all()
    return render(request,'demo3/index.html',{'listp':listp})


def detail(request,id):
    wt=Problem.objects.get(pk=id)
    return render(request,'demo3/detail.html',{'wt':wt})


def poll(request,id):
    try:
        oid=request.POST['wname']
        wt = Problem.objects.get(pk=id)
        xuan=Option.objects.get(pk=oid)
        xuan.oshu+=1
        xuan.save()
        return render(request,'demo3/poll.html',{'wt':wt,'pshu':oid})
    except:

        return HttpResponse('你都没选，还想跑！！！')

dev3/templates/demo3/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static '/css/detail.css' %}">
</head>
<body>
    <div class="kuang">

        <div class="top">
            <h1>{{wt.pname}}</h1>
        </div>
        <div class="bottom">
            <form action="{% url 'demo3:poll' wt.id %}" method="post">
                <ul>
                    {% for i in wt.option_set.all %}
                        <li>{{i.oname}}<input type="radio" name="wname" value="{{i.id}}" ></li>
                    {%endfor%}
                    <input type="submit" value="确定">
                </ul>
            </form>
            <a href="{% url 'demo3:index' %}"><buttom>返回首页</buttom></a>
        </div>
    </div>
</body>
</html>

dev3/templates/demo3/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static '/css/index.css' %}">
</head>
<body>
    <div class="kuang">
        
        <div class="top">
            <h1>问题来了，你是否准备好了吗？？？？</h1>
        </div>
        <div class="bottom">
            <ul>
                {% for i in listp %}
                    <li><a href="{% url 'demo3:detail' i.id %}">{{i.pname}}</a></li>
                {%endfor%}
            </ul>

        </div>
    </div>
</body>
</html>

dev3/templates/demo3/poll.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static '/css/poll.css' %}">
</head>
    <div class="kuang">
<body>

        <div class="top">
            <h1>{{wt.pname}}</h1>
        </div>
        <div class="bottom">
            <form action="">
                <ul>
                    {% for i in wt.option_set.all %}
                        <li>{{i.oname}}的票数:{{i.oshu}}</li>
                    {%endfor%}
                </ul>
            </form>
            <a href="{% url 'demo3:index' %}"><buttom>返回首页</buttom></a>
        </div>
    </div>
</body>
</html>